442 - Tweaks to contribution page banner
AlexsLemonade/scpca-portal pull request #443
Opened 2023-09-18 20:53 UTC by nozomione

## Issue Number
Closing #442

## Purpose/Implementation Notes
Made minor tweaks to contribution page banner. 

@dvenprasad please review the latest UI [here]().

## Types of changes
- Bugfix (non-breaking change which fixes an issue)

## Checklist
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

2023-10-16 15:16 UTC, davidsmejia requested changes
Small change requested looks good though

2023-10-16 15:16 UTC, davidsmejia commented on client/src/components/WarningText.js
> +          name={`Warning${iconNoFill ? 'NoFill' : ''}`}
Can we just have a prop called `iconName` and default it to `WarningNoFill`. Would provide more flexibility and I'm pretty sure we will always use the "no fill" option.

2023-10-16 18:36 UTC, davidsmejia commented on client/src/components/WarningText.js
> +          name={`Warning${iconNoFill ? 'NoFill' : ''}`}
Ah ok, So in that case we should just switch to `iconName` and default it to `Warning` and then for this one use case we pass in `WarningNoFilll`. We won't have to update the other uses of this component and we can now expand it as we need for new iconography.

2023-10-16 18:39 UTC, davidsmejia commented on client/src/images/warning-red.svg
Can we keep the icon file name and icon name matching? So, either rename this to `warning-no-fill` or change the name to be `WarningRed` in `components/icon` to match this file name.

2023-10-16 18:55 UTC, nozomione commented on client/src/images/warning-red.svg
The icon's color is set dynamically using the `iconColor` prop, so I updated the name of the image file to be `warning-no-fill`. Please review,. thank you David.

2023-10-25 15:00 UTC, davidsmejia approved these changes
LGTM

2023-10-25 15:34 UTC, merged