Add Cpy Link Button
AlexsLemonade/scpca-portal pull request #904
Opened 2024-09-23 19:28 UTC by avrohomgottlieb

## Issue Number

https://github.com/AlexsLemonade/scpca-portal/issues/882

## Purpose/Implementation Notes

## Types of changes

C

- New feature (non-breaking change which adds functionality)

## Functional tests

N/A

## Checklist

- [ ] Lint and unit tests pass locally with my changes

## Screenshots

Please attach any screenshots that illustrate these changes.

2024-09-23 19:47 UTC, avrohomgottlieb commented
Still to do for this PR
- Clarify documentation for `HelpLink`
- Debug copy icon not rendering properly

2024-10-01 17:00 UTC, davidsmejia reviewed
LGTM, I made a suggestion with the correct docs link

2024-10-01 18:02 UTC, davidsmejia commented on client/src/hooks/useCopyToClipboard.js
One comment on this, since the state variable has been removed, it doesn't need to be a hook. I would prefer to correct this by adding back in the state variable for the copied text value and just ignore it when destructuring the returned values.

2024-10-01 18:48 UTC, nozomione requested changes
I left a few suggestions/comments, but this PR looks great 🦉🦉🦉!

2024-10-01 18:48 UTC, nozomione commented on client/src/components/DownloadOption.js
> +        <Grid columns={['auto', 'auto']} gap="large">
Add responsiveness to the UI to support mobile view here - please refer to the screenshots!

```suggestion
// import the useResponsive hook in this file
import { useResponsive } from 'hooks/useResponsive' 

export const DownloadOption = ({ computedFile, handleSelectFile }) => {
  const { responsive } = useResponsive() // destructure the 'responsive' method here
  
// use this in the columns prop and pass 'small' and 'big' values 
  <Grid columns={responsive('1', '1/2')} gap="large">
  ```
  
For large devices:

![Screenshot 2024-10-01 at 2 15 28 PM](https://github.com/user-attachments/assets/99205959-97bb-4b02-a03f-9c06610faf20)

On mobile, these buttons are stacked:

![Screenshot 2024-10-01 at 2 15 20 PM](https://github.com/user-attachments/assets/5acb8ded-1da2-4985-9e58-4c4a319ec77f)

2024-10-01 18:48 UTC, nozomione commented on client/src/components/DownloadToken.js
> +    resource && resource.samples ? 'Agree and Continue' : 'Download'
```suggestion
  const buttonLabel = resource?.samples ? 'Agree and Continue' : 'Download'
```
Alternatively, we can use optional chaining to optimize the check above.

2024-10-01 18:48 UTC, nozomione commented on client/src/components/DownloadModal.js
>              />
As chatted in the eng meeting, revert back the condition here, thank you!

2024-10-01 19:08 UTC, nozomione approved these changes

2024-10-01 19:17 UTC, davidsmejia approved these changes
LGTM

2024-10-01 19:19 UTC, merged